### ISSUE TITLE
Failed to install OTA update - DeadObjextException

### ISSUE THREAD

**Issue by Covkie** [chenxiaolong/Custota#60]
![Screenshot_20240613-174528](https://github.com/chenxiaolong/Custota/assets/52550063/b97bac6f-04e3-47f4-8be9-4592341053b3)

[install.log](https://github.com/user-attachments/files/15829102/install.log)
[check.log](https://github.com/user-attachments/files/15829112/check.log)

**Comment by chenxiaolong** [comment]
It looks like Android's `update_engine` component is failing to install the zip because the termux process got killed.

> ```
> OTA URI: content://com.termux.documents/tree/%2Fdata%2Fdata%2Fcom.termux%2Ffiles%2Fhome%2FOTA%2Fwww/document/%2Fdata%2Fdata%2Fcom.termux%2Ffiles%2Fhome%2FOTA%2Fwww%2Fpatched-ota.zip
> ```

When accessing a file from termux (or a cloud provider or any other app that integrates with Android's storage access framework), the app needs to stay running in the background the whole time.

I'd suggest trying to disable battery optimizations for Termux from Android's settings. If that doesn't work, then you're probably out of luck and will need to copy the zip outside of Termux before installing.

**Comment by chenxiaolong** [comment]
> (speaking of, could you add an Android build to the CI for custota_tool and avbroot :). it'd save me needing to compile it myself) Thanks!

Good idea! Added in:

* https://github.com/chenxiaolong/Custota/pull/61
* https://github.com/chenxiaolong/avbroot/pull/304
