### ISSUE TITLE
Custota app crashes on launch (Android 15 B4)

### ISSUE THREAD

**Issue by godspeed0310** [chenxiaolong/Custota#68]
The app crashes on the latest version of Android 15, I've attached logs for your reference. ![crash-com-chiller3-custota-20_07-16-50-35_938.zip](https://github.com/user-attachments/files/16319913/crash-com-chiller3-custota-20_07-16-50-35_938.zip)

**Comment by chenxiaolong** [comment]
Can you upload `/sdcard/Android/data/com.chiller3.custota/files/crash.log`?

Android 15 is not open source yet, so I don't know what changed. However, this looks very much like a bug in the beta where a scheduled job that requests network access is being given a null `Network` instance. If that is the case, there isn't much I can do to work around the problem.

**Comment by chenxiaolong** [comment]
I just upgraded by Pixel Tablet to the Android 15 beta and I can't seem to reproduce the problem.

**Comment by godspeed0310** [comment]
Here's the log file you asked for
[check.log](https://github.com/user-attachments/files/16322267/check.log)

**Comment by chenxiaolong** [comment]
It looks like you uploaded `check.log`. Was there a `crash.log` in that folder?

**Comment by godspeed0310** [comment]
Ah yes there was, I'm really sorry. Here's `crash.log`
[crash.log](https://github.com/user-attachments/files/16323149/crash.log)

**Comment by chenxiaolong** [comment]
Thanks! I added a workaround in #69. Can you give this test build a try? [Custota-4.6.r2.gf454758-release.zip](https://github.com/user-attachments/files/16325848/Custota-4.6.r2.gf454758-release.zip) After installing, you'll have to disable the `Require Unmetered Network` option in Custota.

Since this is an Android bug, there's not much I can do to fix the actual problem. When the bug occurs, Custota will now show a notification instead of crashing:

![Screenshot_20240721-153851](https://github.com/user-attachments/assets/51450c1f-db71-4312-81f5-630254f8d7c3)

Hopefully Google will fix this before the final Android 15 release.

**Comment by godspeed0310** [comment]
Yep the issue seems to be resolved with the build you sent me so I'll close the issue now, tysm for your help

**Comment by chenxiaolong** [comment]
Thanks for testing. The PR has been merged and is included in version 4.7.
